language: ruby

env:
  global:
    - NIL_API_HOST=api.megam.io
    - RUBY_GC_MALLOC_LIMIT=50000000
  matrix:
    - "RAILS_MASTER=0"
    - "RAILS_MASTER=1"

matrix:
  allow_failures:
    - env: "RAILS_MASTER=1"
    - rvm: rbx-2
  fast_finish: true

rvm:
  - 2.3.1

sudo: false

cache:
  directories:
    - vendor/bundle

before_install:
  - gem install bundler
  - npm i -g eslint@2.2 babel-eslint
#  - eslint --ext .es6 app/assets/javascripts
#  - eslint --ext .es6 test/javascripts
  - eslint test/javascripts

install:
  - bash -c "if [ '$RAILS_MASTER' == '1' ]; then bundle update --retry=3 --jobs=3 arel rails; fi"
  - bash -c "if [ '$RAILS_MASTER' == '0' ]; then bundle install --without development --deployment --retry=3 --jobs=3; fi"

script: 'bundle exec rspec && bundle exec rake qunit:test'
