export default Ember.Object.extend({
  APP: "APP",
  SERVICE: "SERVICE",
  MICROSERVICES: "MICROSERVICES",
  ANALYTICS: "ANALYTICS",
  COLLABORATION: "COLLABORATION",
  BITNAMI: "BITNAMI",
  CONTAINERS: "DockerContainer",
  CONTAINER: "container",
});
