#!/bin/sh
./d clean

cd ..
bundle update
bundle install

pkgr package ./ --user=megam --group=megam --maintainer="Thomas Alrin<alrin@megam.co.in>, Raj Thilak <rajthilak@megam.co.in>, Kishorekumar Neelamegam<nkishore@megam.co.in>, Megam Systems <gomegam@megam.co.in>" --runner='upstart-1.5' --dependencies=megamcommon git-core curl bundler rake nginx zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties ruby2.0 --after-install=$HOME/code/megam/workspace/nilavu/script/postinst --before-install=$HOME/code/megam/workspace/nilavu/script/preinst  --auto  --clean --name=megamnilavu --version=0.5 --iteration=1 --buildpacks-cache-dir=$HOME"/code/megam/workspace/nilavu/tmp/buildpacks" --edge  --homepage="http://www.gomegam.com" --description="Nilavu - Web portal for Megam" --license="Apache"
