#!/bin/sh

ln -sf /usr/bin/ruby2.0 /usr/bin/ruby
ln -sf /usr/bin/gem2.0 /usr/bin/gem

mkdir /etc/unicorn
mkdir -p /var/log/megam/megamnilavu
mkdir -p /var/run/megam/megamnilavu

chown megam:megam /var/run/megam/megamnilavu

chown megam:megam /var/log/megam/megamnilavu

cat <<EOF >/etc/nginx/sites-available/nilavu
server {
   listen 443;
   server_name nilavu.mypass.io;

   # SSL configuration
   ssl on;
        ssl_certificate /etc/nginx/certs/nilavu_pub.crt;
        ssl_certificate_key /etc/nginx/private/nilavu.key;

   ssl_session_timeout 5m;
 
   ssl_protocols SSLv3 TLSv1;
   ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP;
   ssl_prefer_server_ciphers on;
 
   # serve assets or request page from proxy (if asset not found)
   location / {
      try_files \$uri @proxy;
   }
 
   # the play web server
   location @proxy {
      proxy_pass  http://localhost:8080;
      proxy_redirect off;
      proxy_buffering off;
 
      #send protocol info to play server
      proxy_set_header        Host               \$host;
      proxy_set_header        X-Real-IP          \$remote_addr;
      proxy_set_header        X-Forwarded-Proto  https;
      proxy_set_header        X-Forwarded-Ssl    on;
      proxy_set_header        X-Forwarded-For    \$proxy_add_x_forwarded_for;
   }
}

EOF

mkdir -p /etc/nginx/private &&
mkdir -p /etc/nginx/certs &&

openssl req -x509 -nodes -days 365 -newkey rsa:1024 \
-keyout /etc/nginx/private/nilavu.key \
-out /etc/nginx/certs/nilavu_pub.crt <<EOF
IN
TN
Private

Megam Nilavu Portal
Development
nilavu.mypaas.io

EOF

cp /etc/nginx/private/nilavu.key /usr/share/megam/megamnilavu/conf
cp /etc/nginx/certs/nilavu_pub.crt /usr/share/megam/megamnilavu/conf

ln -s /etc/nginx/sites-available/nilavu /etc/nginx/sites-enabled/nilavu


cat > /etc/unicorn/nilavu.rb <<EOF

##
# Unicorn config at /etc/unicorn/nilavu.rb
##

# What ports/sockets to listen on, and what options for them.
listen "8080", :tcp_nodelay => true, :backlog => 100

working_directory '/usr/share/megam/megamnilavu'

pid "/var/run/megam/megamnilavu/nilavu.pid"

stdout_path "/var/log/megam/megamnilavu/nilavu_out.log"
stderr_path "/var/log/megam/megamnilavu/nilavu_err.log"

# What the timeout for killing busy workers is, in seconds
timeout 60

# Whether the app should be pre-loaded
preload_app false

# How many worker processes
worker_processes 8


# Run forked children as specified user/group
user "megam", "megam"


# What to do before we fork a worker
before_fork do |server, worker|
  sleep 1
end

EOF


cat > //etc/init/megamnilavu.conf <<EOF
# Configuration Upstart file for Nilavu
description "Upstart script for nilavu"

start on (local-filesystems)
stop on runlevel [!12345]


pre-start script


end script


respawn

exec start-stop-daemon --start --chdir "/usr/share/megam/megamnilavu/" --exec /usr/bin/bundle exec unicorn_rails -- -E production -c "/etc/unicorn/nilavu.rb"
EOF

cat > //usr/share/megam/megamnilavu/production.log <<EOF
test log
EOF

chmod 666 /usr/share/megam/megamnilavu/production.log

chown -R megam:megam /usr/share/megam/megamnilavu

chdir /usr/share/megam/megamnilavu

echo "setting up database"
rake db:migrate

#setup a host name nilavu.some.com
echo "127.0.0.1 nilavu.mypaas.io megamnilavu" >> /etc/hosts

echo "starting megamnilavu"
sudo start megamnilavu
echo "started"

initctl reload-configuration

service nginx restart


