#!/bin/sh
#apt-get -y update
#apt-get -y -f install
echo "Ruby version before==> "
ruby -v
ln -sf /usr/bin/ruby2.0 /usr/bin/ruby
ln -sf /usr/bin/gem2.0 /usr/bin/gem
echo "Ruby version after==> "
ruby -v

mkdir /etc/unicorn
mkdir -p /var/log/megam/nilavu
mkdir -p /var/run/megam/nilavu

if ! getent group megam > /dev/null 2>&1
then
    echo "Creating system group: megam"
	addgroup --system megam
fi

# Adding megam
if ! id -u megam > /dev/null 2>&1; then
    echo "Creating user megam in group megam"
    useradd --system --no-create-home --gid megam --shell /bin/false megam
fi

chown megam:megam /var/run/megam/nilavu

chown megam:megam /var/log/megam/nilavu

cat <<EOF >/etc/nginx/sites-available/nilavu
upstream nilavu {
	server 127.0.0.1:8080;
}

server {
   listen 80;
   rewrite ^ https://localhost$request_uri? permanent;
	server_name localhost;
}

server {
	listen 443;
	server_name localhost;

	access_log /var/log/megam/nilavu.log;
	root /opt/nilavu/public;

   # SSL configuration
   ssl on;
        ssl_certificate /etc/nginx/certs/nilavu_pub.crt;
        ssl_certificate_key /etc/nginx/private/nilavu.key;
   ssl_session_timeout 5m;
 
   ssl_protocols SSLv3 TLSv1;
   ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP;
   ssl_prefer_server_ciphers on;

	location / {
		proxy_pass http://nilavu;
		proxy_redirect     off;
		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
	}

	# if 502 Bad Gateway or 504 Gateway Timeout show the 500.html page
	# if 503 Service Unavailable show the maintenance.html page
	error_page 504 502 /500.html;
	error_page 503 @maintenance;
        if (-f $document_root/maintenance.html) {
                return 503;
        }
	location @maintenance {
		rewrite ^(.*)$ /maintenance.html break;
	}
	
}
EOF

mkdir -p /etc/nginx/private &&
mkdir -p /etc/nginx/certs &&

openssl req -x509 -nodes -days 365 -newkey rsa:1024 \
-keyout /etc/nginx/private/nilavu.key \
-out /etc/nginx/certs/nilavu_pub.crt <<EOF
IN
TN
Private

Megam Nilavu Portal
Development
nilavu.co

EOF

cp /etc/nginx/private/nilavu.key ./conf
cp /etc/nginx/certs/nilavu_pub.crt ./conf

ln -s /etc/nginx/sites-available/nilavu /etc/nginx/sites-enabled/nilavu



#gem install bundler --no-doc
#gem install unicorn --no-doc

cat > /etc/unicorn/nilavu.rb <<EOF

##
# Unicorn config at /etc/unicorn/nilavu.rb
# Managed by Chef - Local Changes will be Nuked from Orbit (just to be sure)
##

# What ports/sockets to listen on, and what options for them.
listen "8080", :tcp_nodelay => true, :backlog => 100

working_directory '/opt/nilavu'

pid "/var/run/megam/nilavu/unicorn_nilavu.pid"

stdout_path "/var/log/megam/nilavu/nilavu_out.log"
stderr_path "/var/log/megam/nilavu/nilavu_err.log"

# What the timeout for killing busy workers is, in seconds
timeout 60

# Whether the app should be pre-loaded
preload_app false

# How many worker processes
worker_processes 8


# Run forked children as specified user/group
user "megam", "megam"


# What to do before we fork a worker
before_fork do |server, worker|
  sleep 1
end

EOF


cat > //etc/init/unicorn_nilavu.conf <<EOF
# Dynamically generated by Chef on ip-144-76-190-227.podnix.com
# Local modifications will be overwritten by Chef.
description "unicorn for nilavu"

start on (local-filesystems)
stop on runlevel [!12345]


pre-start script


end script


respawn

exec start-stop-daemon --start --chdir "/opt/nilavu/" --exec /usr/local/bin/bundle exec unicorn_rails -- -E production -c "/etc/unicorn/nilavu.rb"
EOF

cat > //opt/nilavu/production.log <<EOF
test log
EOF

chmod 666 /opt/nilavu/production.log

chown -R megam:megam /opt/nilavu
cd /opt/nilavu
rake db:migrate

echo "starting unicorn_nilavu"
sudo start unicorn_nilavu
echo "started"

initctl reload-configuration

service nginx restart


