#!/bin/sh
ln -sf /usr/bin/ruby2.0 /usr/bin/ruby
ln -sf /usr/bin/gem2.0 /usr/bin/gem

mkdir /etc/unicorn
mkdir -p /var/log/megam/megamnilavu
mkdir -p /var/run/megam/megamnilavu

chown megam:megam /var/run/megam/megamnilavu

chown megam:megam /var/log/megam/megamnilavu

cat <<EOF >/etc/nginx/sites-available/nilavu
upstream nilavu {
	server 127.0.0.1:8080;
}

server {
   listen 80;
   rewrite ^ https://nilavu.mypaas.io$request_uri? permanent;
   server_name nilavu.some.com;
}

server {
	listen 443;
	server_name nilavu.mypaas.io;

	access_log /var/log/megam/megamnilavu.log;
	root /usr/share/megam/megamnilavu/public;

   # SSL configuration
   ssl on;
        ssl_certificate /etc/nginx/certs/nilavu_pub.crt;
        ssl_certificate_key /etc/nginx/private/nilavu.key;
   ssl_session_timeout 5m;

   ssl_protocols SSLv3 TLSv1;
   ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP;
   ssl_prefer_server_ciphers on;

	location / {
		proxy_pass http://nilavu;
		proxy_redirect     off;
		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
	}

	# if 502 Bad Gateway or 504 Gateway Timeout show the 500.html page
	# if 503 Service Unavailable show the maintenance.html page
	error_page 504 502 /500.html;
	error_page 503 @maintenance;
        if (-f $document_root/maintenance.html) {
                return 503;
        }
	location @maintenance {
		rewrite ^(.*)$ /maintenance.html break;
	}

}
EOF

mkdir -p /etc/nginx/private &&
mkdir -p /etc/nginx/certs &&

openssl req -x509 -nodes -days 365 -newkey rsa:1024 \
-keyout /etc/nginx/private/nilavu.key \
-out /etc/nginx/certs/nilavu_pub.crt <<EOF
IN
TN
Private

Megam Nilavu Portal
Development
nilavu.mypaas.io

EOF

cp /etc/nginx/private/nilavu.key ./conf
cp /etc/nginx/certs/nilavu_pub.crt ./conf

ln -s /etc/nginx/sites-available/nilavu /etc/nginx/sites-enabled/nilavu


cat > /etc/unicorn/nilavu.rb <<EOF

##
# Unicorn config at /etc/unicorn/nilavu.rb
##

# What ports/sockets to listen on, and what options for them.
listen "8080", :tcp_nodelay => true, :backlog => 100

working_directory '/usr/share/megam/megamnilavu'

pid "/var/run/megam/megamnilavu/nilavu.pid"

stdout_path "/var/log/megam/megam/megamnilavu/nilavu_out.log"
stderr_path "/var/log/megam/megam/megamnilavu/nilavu_err.log"

# What the timeout for killing busy workers is, in seconds
timeout 60

# Whether the app should be pre-loaded
preload_app false

# How many worker processes
worker_processes 8


# Run forked children as specified user/group
user "megam", "megam"


# What to do before we fork a worker
before_fork do |server, worker|
  sleep 1
end

EOF


cat > //etc/init/megamnilavu.conf <<EOF
# Configuration Upstart file for Nilavu
description "Upstart script for nilavu"

start on (local-filesystems)
stop on runlevel [!12345]


pre-start script


end script


respawn

exec start-stop-daemon --start --chdir "/usr/share/megam/megamnilavu/" --exec /usr/local/bin/bundle exec unicorn_rails -- -E production -c "/etc/unicorn/nilavu.rb"
EOF

cat > //usr/share/megam/megamnilavu/production.log <<EOF
test log
EOF

chmod 666 /usr/share/megam/megamnilavu/production.log

chown -R megam:megam /usr/share/megam/megamnilavu

chdir /usr/share/megam/megamnilavu

echo "setting up database"
rake db:migrate

#setup a host name nilavu.some.com
sed -i "127.0.0.1 nilavu.mypaas.io   megamnilavu" /etc/hosts

echo "starting nilavu.mypaas.io"
sudo start megamnilavu
echo "started"

initctl reload-configuration

service nginx restart
