#!/usr/bin/env bash

fmtcount=`find . -name *.*~ 2>&1 | wc -l`
if [ $fmtcount -gt 0 ]; then
    echo "Some files are temporary files, please run 'find . -type f -name "*.*~" -exec rm -f {} \;' to delete them before committing"
    exit 1
fi

asstcount=`rake assets:precompile RAILS_ENV=production | wc -l`
if [ $asstcount -gt 0 ]; then
    echo "Some files don't pass precompile, please run 'rake assets:precompile RAILS_ENV=production' to precompile successfully before committing"
    exit 1
fi
exit 0
